import type { Block, BlockType } from "./types";

export interface SlashCommand {
  id: string;
  label: string;
  description: string;
  icon: string;
  aliases: string[];
  category: "basic" | "media" | "advanced" | "database" | "embed" | "layout";
  action: "convert" | "insert";
  blockType?: BlockType;
  extra?: Record<string, unknown>;
  custom?: "page" | "sub-page" | "database-inline" | "database-page" | "image" | "video" | "audio" | "file" | "embed" | "bookmark" | "columns" | "callout" | "code" | "math";
}

export const SLASH_COMMANDS: SlashCommand[] = [
  // BASIC TEXT
  {
    id: "text",
    label: "Text",
    description: "Just start writing with plain text.",
    icon: "📝",
    aliases: ["text", "paragraph", "p"],
    category: "basic",
    action: "convert",
    blockType: "text",
  },
  {
    id: "h1",
    label: "Heading 1",
    description: "Big section heading.",
    icon: "H₁",
    aliases: ["heading 1", "h1", "#"],
    category: "basic",
    action: "convert",
    blockType: "heading-1",
  },
  {
    id: "h2",
    label: "Heading 2",
    description: "Medium section heading.",
    icon: "H₂",
    aliases: ["heading 2", "h2", "##"],
    category: "basic",
    action: "convert",
    blockType: "heading-2",
  },
  {
    id: "h3",
    label: "Heading 3",
    description: "Small section heading.",
    icon: "H₃",
    aliases: ["heading 3", "h3", "###"],
    category: "basic",
    action: "convert",
    blockType: "heading-3",
  },
  {
    id: "bullet",
    label: "Bulleted list",
    description: "Create a simple bulleted list.",
    icon: "•",
    aliases: ["bullet", "list", "ul", "-"],
    category: "basic",
    action: "convert",
    blockType: "bullet-list",
  },
  {
    id: "numbered",
    label: "Numbered list",
    description: "Create a numbered list.",
    icon: "1.",
    aliases: ["numbered", "ol", "1.", "number"],
    category: "basic",
    action: "convert",
    blockType: "numbered-list",
  },
  {
    id: "todo",
    label: "To-do",
    description: "Track tasks with checkboxes.",
    icon: "☑️",
    aliases: ["todo", "to-do", "task", "[]"],
    category: "basic",
    action: "convert",
    blockType: "todo",
  },
  {
    id: "toggle",
    label: "Toggle list",
    description: "Hide content within a toggle.",
    icon: "▶",
    aliases: ["toggle", ">"],
    category: "basic",
    action: "convert",
    blockType: "toggle",
  },
  {
    id: "quote",
    label: "Quote",
    description: "Capture a quote.",
    icon: "❝",
    aliases: ["quote", "blockquote"],
    category: "basic",
    action: "convert",
    blockType: "quote",
  },
  {
    id: "divider",
    label: "Divider",
    description: "Visually divide blocks.",
    icon: "—",
    aliases: ["divider", "hr", "---"],
    category: "basic",
    action: "convert",
    blockType: "divider",
  },
  {
    id: "callout",
    label: "Callout",
    description: "Make writing stand out with an icon.",
    icon: "💡",
    aliases: ["callout", "info", "warning"],
    category: "basic",
    action: "convert",
    blockType: "callout",
  },
  {
    id: "page",
    label: "Page",
    description: "Embed a sub-page inside this page.",
    icon: "📄",
    aliases: ["page", "subpage"],
    category: "basic",
    action: "insert",
    custom: "page",
  },
  {
    id: "code",
    label: "Code",
    description: "Capture a code snippet.",
    icon: "</>",
    aliases: ["code", "```"],
    category: "basic",
    action: "convert",
    blockType: "code",
  },

  // TOGGLE HEADINGS
  {
    id: "toggle-h1",
    label: "Toggle heading 1",
    description: "Heading with toggleable content.",
    icon: "▼ H₁",
    aliases: ["toggle h1", "toggle heading 1"],
    category: "basic",
    action: "convert",
    blockType: "toggle-heading-1",
  },
  {
    id: "toggle-h2",
    label: "Toggle heading 2",
    description: "Heading with toggleable content.",
    icon: "▼ H₂",
    aliases: ["toggle h2", "toggle heading 2"],
    category: "basic",
    action: "convert",
    blockType: "toggle-heading-2",
  },
  {
    id: "toggle-h3",
    label: "Toggle heading 3",
    description: "Heading with toggleable content.",
    icon: "▼ H₃",
    aliases: ["toggle h3", "toggle heading 3"],
    category: "basic",
    action: "convert",
    blockType: "toggle-heading-3",
  },

  // MEDIA
  {
    id: "image",
    label: "Image",
    description: "Upload or embed an image.",
    icon: "🖼️",
    aliases: ["image", "img", "picture"],
    category: "media",
    action: "insert",
    custom: "image",
  },
  {
    id: "video",
    label: "Video",
    description: "Embed a YouTube/Vimeo/Loom video.",
    icon: "🎬",
    aliases: ["video"],
    category: "media",
    action: "insert",
    custom: "video",
  },
  {
    id: "audio",
    label: "Audio",
    description: "Embed an audio file or stream.",
    icon: "🎵",
    aliases: ["audio"],
    category: "media",
    action: "insert",
    custom: "audio",
  },
  {
    id: "file",
    label: "File",
    description: "Upload or embed a file.",
    icon: "📎",
    aliases: ["file", "attachment"],
    category: "media",
    action: "insert",
    custom: "file",
  },
  {
    id: "embed",
    label: "Embed",
    description: "Embed external content (Iframely-style).",
    icon: "🔗",
    aliases: ["embed", "iframe"],
    category: "embed",
    action: "insert",
    custom: "embed",
  },
  {
    id: "bookmark",
    label: "Web bookmark",
    description: "Save a link as a visual bookmark.",
    icon: "🔖",
    aliases: ["bookmark", "link"],
    category: "embed",
    action: "insert",
    custom: "bookmark",
  },

  // ADVANCED
  {
    id: "table",
    label: "Simple table",
    description: "Quick table for tabular content.",
    icon: "▦",
    aliases: ["table", "grid"],
    category: "advanced",
    action: "convert",
    blockType: "table",
  },
  {
    id: "toc",
    label: "Table of contents",
    description: "Auto-generated from headings.",
    icon: "≡",
    aliases: ["toc", "table of contents"],
    category: "advanced",
    action: "convert",
    blockType: "table-of-contents",
  },
  {
    id: "breadcrumb",
    label: "Breadcrumb",
    description: "Show hierarchical path.",
    icon: "›",
    aliases: ["breadcrumb"],
    category: "advanced",
    action: "convert",
    blockType: "breadcrumb",
  },
  {
    id: "math",
    label: "Block equation",
    description: "LaTeX math block.",
    icon: "∑",
    aliases: ["math", "equation", "latex"],
    category: "advanced",
    action: "convert",
    blockType: "equation",
  },
  {
    id: "synced",
    label: "Synced block",
    description: "Mirror content across pages.",
    icon: "🔄",
    aliases: ["synced", "sync"],
    category: "advanced",
    action: "convert",
    blockType: "synced-block",
  },
  {
    id: "ai",
    label: "AI block",
    description: "Generate content with AI.",
    icon: "✨",
    aliases: ["ai", "ask"],
    category: "advanced",
    action: "convert",
    blockType: "ai-block",
  },
  {
    id: "button",
    label: "Button",
    description: "One-click actions.",
    icon: "▶",
    aliases: ["button"],
    category: "advanced",
    action: "convert",
    blockType: "button",
  },

  // LAYOUT
  {
    id: "columns-2",
    label: "2 columns",
    description: "Side-by-side layout.",
    icon: "▥",
    aliases: ["columns", "2 columns", "2col"],
    category: "layout",
    action: "insert",
    custom: "columns",
    extra: { columns: 2 },
  },
  {
    id: "columns-3",
    label: "3 columns",
    description: "Three-column layout.",
    icon: "▥",
    aliases: ["3 columns", "3col"],
    category: "layout",
    action: "insert",
    custom: "columns",
    extra: { columns: 3 },
  },
  {
    id: "columns-4",
    label: "4 columns",
    description: "Four-column layout.",
    icon: "▥",
    aliases: ["4 columns", "4col"],
    category: "layout",
    action: "insert",
    custom: "columns",
    extra: { columns: 4 },
  },

  // DATABASE
  {
    id: "db-table",
    label: "Table — Inline",
    description: "Add a database table inline.",
    icon: "▦",
    aliases: ["database", "table", "db", "/db"],
    category: "database",
    action: "insert",
    custom: "database-inline",
    extra: { view: "table" },
  },
  {
    id: "db-board",
    label: "Board — Inline",
    description: "Add a Kanban board inline.",
    icon: "▤",
    aliases: ["board", "kanban"],
    category: "database",
    action: "insert",
    custom: "database-inline",
    extra: { view: "board" },
  },
  {
    id: "db-calendar",
    label: "Calendar — Inline",
    description: "Calendar database inline.",
    icon: "📅",
    aliases: ["calendar"],
    category: "database",
    action: "insert",
    custom: "database-inline",
    extra: { view: "calendar" },
  },
  {
    id: "db-list",
    label: "List — Inline",
    description: "List database inline.",
    icon: "≣",
    aliases: ["list"],
    category: "database",
    action: "insert",
    custom: "database-inline",
    extra: { view: "list" },
  },
  {
    id: "db-gallery",
    label: "Gallery — Inline",
    description: "Card-based gallery.",
    icon: "▢",
    aliases: ["gallery"],
    category: "database",
    action: "insert",
    custom: "database-inline",
    extra: { view: "gallery" },
  },
  {
    id: "db-timeline",
    label: "Timeline — Inline",
    description: "Gantt-style timeline.",
    icon: "⇆",
    aliases: ["timeline", "gantt"],
    category: "database",
    action: "insert",
    custom: "database-inline",
    extra: { view: "timeline" },
  },
  {
    id: "db-chart",
    label: "Chart — Inline",
    description: "Visualise data.",
    icon: "📊",
    aliases: ["chart"],
    category: "database",
    action: "insert",
    custom: "database-inline",
    extra: { view: "chart" },
  },
  {
    id: "db-form",
    label: "Form — Inline",
    description: "Collect data via a form.",
    icon: "🧾",
    aliases: ["form"],
    category: "database",
    action: "insert",
    custom: "database-inline",
    extra: { view: "form" },
  },
];

export function filterSlash(query: string): SlashCommand[] {
  const q = query.toLowerCase().trim();
  if (!q) return SLASH_COMMANDS;
  return SLASH_COMMANDS.filter(
    (cmd) => cmd.label.toLowerCase().includes(q) || cmd.aliases.some((a) => a.includes(q)),
  );
}
