// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isuqldoryaqznbhkfmsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdXFsZG9yeWFxem5iaGtmbXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1ODcxMzQsImV4cCI6MjA5NDE2MzEzNH0.fv2xHkIIbQL_sEx5RyNalhfA_Ysx2Dk06MoGZ7T3V1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});